apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: sync
spec:
  project: default
  source:
    repoURL: https://github.com/CelPyn/homelab.git
    targetRevision: HEAD
    path: apps

  destination:
    server: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
