---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Jellyfin is the volunteer-built media solution that puts you in control of your media.
    gethomepage.dev/group: Media
    gethomepage.dev/icon: jellyfin.png
    gethomepage.dev/name: Jellyfin
    gethomepage.dev/widget.type: "jellyfin"
    gethomepage.dev/widget.url: "https://jellyfin.home.pynenborg.com"
    gethomepage.dev/widget.enableBlocks: "true"
    gethomepage.dev/widget.key: "6450afab16e94ee5a69c4687033ab675"
    gethomepage.dev/pod-selector: ""
spec:
  rules:
    - host: "jellyfin.home.pynenborg.com"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: jellyfin
                port:
                  number: 80
  tls:
    - hosts:
        - "jellyfin.home.pynenborg.com"
      secretName: jellyfin-home-cert
