apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
commonLabels:
  app.kubernetes.io/name: jellyfin
  app.kubernetes.io/part-of: jellyfin
  app.kubernetes.io/managed-by: argocd
resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - pvc.yaml
