apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
    - Social:
        - Reddit:
            - icon: reddit.png
              href: https://reddit.com/
              description: The front page of the internet
    - Entertainment:
        - YouTube:
            - icon: youtube.svg
              abbr: YT
              href: https://youtube.com/
    - Monitoring & Management:
        - ArgoCD:
            - icon: argocd.png
              href: https://argo.home.pynenborg.com/
              description: ArgoCD is a declarative, GitOps continuous delivery tool for Kubernetes.
  services.yaml: |
    - Media:
        - Jellyfin:
            - icon: jellyfin.png
              href: https://netflix.home.pynenborg.com/
              description: Jellyfin is the volunteer-built media solution that puts you in control of your media.
              widget:
                type: jellyfin
                url: https://netflix.home.pynenborg.com
                key: 6450afab16e94ee5a69c4687033ab675
                enableBlocks: true # optional, defaults to false
                enableNowPlaying: true # optional, defaults to true

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
