apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
commonLabels:
  app.kubernetes.io/name: homepage
  app.kubernetes.io/part-of: homepage
  app.kubernetes.io/managed-by: argocd
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - rbac.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
