---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: aws-creds
  namespace: cert-manager
spec:
  encryptedData:
    accessKeyId: AgB1VHcM5N5+iJaMd7awvnYW5g6qGiASNm2zZick2TMFI/WDhJoECacBd1JYmzWBLyYfOnMLLcJRqnlzTJBictFDcQoILEnunWbI/2DW0X9ir1zRTcVfPytJ1JErVlLo4ehkEBsdSC7J536GZf4LgdKDjEf731qrXhIPdno0E/dAOtTejQ63yag/+d5oJJ2FLv8krBf1pGZQcw7IJl4kJc8AQ9SI0hTIJTkA+ShIgMAwaeF9iIxt2v7/NZmwXpgRx0KJvcmlNst2dRIGUqpTtEHpn+7y1DtxDAhsRoF40iUWAZcezlGYloL4i80XO1dzbeIDkBVGSZyejjYOPyH2gJR5NciVu1opt5FgZisqOPvgXL6Owvu7v2YS13L3S9Xnf4ySs/TUc37I7MVhSU4LX+rvOIvdUP382dSMLlUO4ZUhHullgVHJP0c69+aXxFKQQ3AWguOx127v1Hstgn3VODVlBY2qrFpyXqnkmYYJOX8Ffa8f2eLQ5tS3GYK0BGI0GT1KPrhqgM/cI88BM44j7DxOKvR4uNEv1dxYNYvpNG6KW1G/HZqhLiajqvDHJEJ6C+aRgkDCSKXyFsRiuWwXhkq2e1qTQV1fMm0wQtiZL+6nOT3KVYrmbB+kziyjQ0pesBC57JfkGvwxvVk5F/GZ6MxjEsIoYQGSrbDiKsyswqlEwRieukHEvccFEXxuVuOwCo11UVlJhk88fYYNrKLVccdklpcyQA==
    secretAccessKey: AgCY5bioKSBhdMELikL2nF3gGG9Vyi6Mnk5cbg2HGZ0dLDqYwHF4rfhYz5ch1HBZHSaT/u7SnCt/JU5R/sCidrwQ5hOSLGDcnlzxcXewpeA6+RsEwGJ5oeoQtIJAYkTboqCFryVdumno0mYyMSZNrI/lxcmtpvypw4eOU7A+0RICNfNjO3xvcMPVuycyeABTnM3fQAuRBGqugUtENo55VeAYLAOOJyJ0eYva68rsH+1xYqMOgvg9S+FRTMCF/OS7NH4Le8tLtwHzOPOEcaqgA/zSPJUPDcKuJuH45WgAioiSGqDGH2mrYy6EYH6fxogDNpBfURILH3uQvl2eQFOxZe1vCBzyWwsvTIhd0Q8my9jO/LoH9BTCh+1IoPNtcbYwCx/oPnemFAvX1wLhZGdZmazQDoJ9SjCanRm2tHcjthIKSSP216XCZIUYN6PQxSYiivAz0DlmvG1plX5CdsdgLQTqK6c9fLFEYOiHZecRxCCDL7ZMZLJzcRCo7Pz1GPNwQgOCXqY7HrTtzz+0Jxs5ugJqJi5nNdZdlvZRoHyFseuYBZ9AHIBCm2Q2UjtRbYu7MsGoYa3Wk60EvOEsUnpjWSC+ghbFJexKOTAP4ocr3BUg4hHeZQtjMT7Tmo552ycRMSyZX37B4pj4l0E0SSBfdyanZUCFn2vkc/srefMuX6xlQ+1HBLdX3nYvYFzlNV2YsYRNTBkHTYrfdELejT1tfiUlM+vjgExVA05T5HPvij4gamrFU+JSVG3H
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: aws-creds
      namespace: cert-manager
