---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: cert-manager
spec:
  encryptedData:
    accessKeyId: AgC6UhsrgzHWxyweLv9/m5pG/xuIOLHqHrs4J/95Inm1aykmHgoSdrGm2rpyKsYTlySp+fHHDpnLv489PDX3F6ZEr2HPxl/hKbhxtwUpJd+OHE3a3WDp7Za1wV5lD7aDBaQdgzSmMieA75UY10C1M58/BN17vVr7Wd4T6J+jAurRNDQefcMXj4JTdiLffzkvDdKLW6L4urGcKSpYpDzsQ2q9RyWc1Urv4mK9rZ0lMuHQFTQvVlv4/rTu5p2QS/P7iDr/rIsSSOSbUgtTLbUFsRC1WEn3Jwl+TJgX29AZgvRYH5mfhoVrnwQsi0y95DO46IwCdGqa9woxDhuk+ML5+b4v7XaKAjXpOPOvB+z4WC8PwLWXlQ51RxMxyOJ0vxofucrp6oLgGA4NXar92+s2UrmhDdwa2CHMSUgUYtZOLhAihukGban2Ail+T7KsrG1AHQa+XLwg/m1HBzYK+FdKXxZGozd0nmvmV5L/WI2QLaIm1Q48dIr07PsDowu8gSrfJkAmQpfzPF2sHmVYNluQpIXfaPkdB/k/7w9Jx12Lnpa0q+rj/DDo5x+XcIDJcGHAW4Jj3MDiQ5Fccy6Pd+zKOPwVT+lXmBQeczmaw7E+SQEDjsa4aJQenqc6NKg5nON2LSmsEkTnsrKfVDvvoMh186Kbda+Jrd3SjDgOqWLIs5bbd1ubgP6dyVRdZIN8AcCPFHgcws4n/oOWqftloZ6N3JUCJxZQCg==
    secretAccessKey: AgAs/anOcX0qgz3fzTmWUgDDBEHTAIy4VpAGXKDq+YtGHioj4Gip8mmTufxVryePBoIR5Rx1mMj6a6xBjrMLeuhNfExqoK0wm4ZRlw4SIxbrBdaExPT6s56GtWaX6IVRmbFQt1a5+LRROW/F3PXtQBBHxaruoQbTbbXigPKt7EG9TNx7iKjSgZB0F4C1QFDC8FHaOe5vTSmMxlQ0aKzlfe5uMTEgszLgpn5deVHvz61x6nzvRuOzJQvH3C66qwVNOB7byummbcJTVEyFIGYbFEmwb/D7xjTA+B80mMFSr69y05neE+ATjDyeFWV6M/yQ4L+EKGk/wsCfZ3OSSFF1wGMO4izmtEhE0GoGIHWvW2JgDbZwm+USvppboz5yJepdhfaAC5jBu4ZOQVRCm4QWhqopZK9Zc2OiylyLzZg4u+beV88+qGbt9Oa+lr68a0HFSZAU/igFEmLWSvxs94YryQa7rXkyPa9j48/MTw9cQgw6kT4ML5YZdPbRKmhQxQLbYB0LU7qIJXg+HoI49h/HBOl4ARNGJmWlR9ZnWq+p88yYSs1Inhaavh2Yec235sesurMNdl9SsUMGxpqlyUMucfFe7o3Xd+Zyz/5QF+HClUEbPeSZoBZ+zfZW5IZnyAtDmpJFv3eTuGBg0xWXE10O52Ele3PdTpF2OJtD0Daq0bXRY0A6LcuqR0zFAGUFqU42IeGHrcuaB+SR5NsjFnsyHJXGv8O3G8ZELZ4rWSfb3ZTYSGLdhxk/l6lu
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: cert-manager
