apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-local-path
  annotations:
    defaultVolumeType: hostPath
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
