apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-local-path
  namespace: kube-system
  annotations:
    defaultVolumeType: hostPath
provisioner: rancher.io/local-path
parameters:
  # Be sure to edit the config.json in local-path-config configmap to allow the following path
  nodePath: /mnt
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
