apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app.kubernetes.io/part-of: core
  app.kubernetes.io/managed-by: argocd
resources:
  - hdd-storage.yaml
  - aws-creds.sealed.yaml
  - cluster-issuer.yaml
