apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: core
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "pynenborg_home_notifications"
spec:
  project: default
  source:
    repoURL: https://github.com/CelPyn/homelab.git
    targetRevision: HEAD
    path: infrastructure

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
