- op: replace
  path: /data/config.json
  value: |-
    {
      "nodePathMap":[
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":["/var/lib/rancher/k3s/storage"]
        },
        {
          "node":"leviathan",
          "paths":["/mnt"]
        }
      ]
    }
